version: '3'

services:
  app:
    build: .
    command: rails s --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
